"use client";
import "./globals.css";
import Nav from "./Nav";
import { RecoilRoot } from "recoil";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RecoilRoot>
          <Nav></Nav>
          <main className="min-h-screen flex flex-col justify-start pt-12 items-center bg-slate-100 bg-white">
            {children}
          </main>
        </RecoilRoot>
      </body>
    </html>
  );
}
